TOP_CITIES = [
    "New York City, United States",
    "Paris, France",
    "Rome, Italy",
    "London, United Kingdom",
    "Jerusalem, Israel",
    "Bangkok, Thailand",
    "Prague, Czech Republic",
    "Berlin, Germany",
    "Amsterdam, Netherlands",
    "Madrid, Spain",
    "Munich, Germany",
    "Vienna, Austria",
    "Washington DC, United States",
    "Brussels, Belgium",
    "Tel Aviv, Israel",
    "Barcelona, Spain",
    "Istanbul, Turkey",
    "Sydney, Australia",
    "Rio De Janeiro, Brazil",
    "Venice, Italy",
    "Budapest, Hungary",
    "Seville, Spain",
    "Granada, Spain",
    "San Francisco, United States",
    "Cape Town, South Africa",
    "Hong Kong, China",
    "Buenos Aires, Argentina",
    "Florence, Italy",
    "Tokyo, Japan",
    "Cairo, Egypt",
    "Toronto, Canada",
    "Athens, Greece",
    "Melbourne, Australia",
    "Kathmandu, Nepal",
    "Montreal, Canada",
    "Edinburgh, United Kingdom",
    "Hanoi, Vietnam",
    "Singapore",
    "Dublin, Ireland",
    "Mexico City, Mexico",
]